# Build stage
FROM node:20-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages ./packages
COPY apps ./apps

RUN npm ci
RUN npm run build -w web

# Production stage
FROM node:20-slim AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package.json package.json
COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/apps/web apps/web
COPY --from=builder /app/packages packages

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["npm", "run", "start"]
